### ISSUE TITLE
Logo Proposal for DumpsterDiver

### ISSUE THREAD

**Issue by leonardoderoy** [securing/DumpsterDiver#6]
Hello! @securing

I'm a graphic designer and I like to support your project because I believe a good logo that reflects your project at its best can help the project publicity and trustability, also i'm an open source enthusiast. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Leonardo Deroy

Graphic Designer

**Comment by xep624** [comment]
Hi Leonardo!

Great idea - that would be awesome to have a logo for this project! If you once have a flow of creativity and some spare time please create some graphics. Can't wait for it!!!

Cheers!
Pawel.

**Comment by leonardoderoy** [comment]
Hi @xep624 ok perfect, I would like to know what is your project exactly and the exact name would be very helpful

**Comment by xep624** [comment]
The name of the project is "DumpsterDiver" - the name refers to the attack called "dumpster-diving". Dumpster diving is a method of obtaining information about a company just by examining their trash.This technique was very popular especially back in the 90’s where many old school hackers like Kevin Mitnick had managed to hack major companies just by discovering critical information through their garbage.

This project is a cyber representation of dumpster-diving. Basically company's internal, shared storage looks like a dumpster full of garbage (any kind of file) and usually there is no single person in whole company who can say what exactly is stored there. The tool DumpsterDiver analyze all kind of files in search of any hardcoded passwords and any sensitive information. 

Let me know if you need any other info ;)

**Comment by leonardoderoy** [comment]
Hellow @xep624   Ok I will be uploading some proposals soon

**Comment by xep624** [comment]
Hi @leonardoderoy , just the follow up - did you have any chance to create any logo?

**Comment by noveoko** [comment]
Hi. If this is still open let me know. I will gladly take over the logo project.

**Comment by xep624** [comment]
Hi @noveoko ! Absolutely it is still open and it would be awesome if you can handle the logo :) Thank you!

**Comment by noveoko** [comment]
![dumpster_diver_logo](https://user-images.githubusercontent.com/1831478/48984265-ef78e280-f0f9-11e8-9d9f-cb30391f8caa.png)

Please let me know if this works. If not I can take your feedback and go in another direction. :)

**Comment by xep624** [comment]
Thanks @noveoko. I think it should more suggest the idea of the tool, e.g. something like this: https://www.gograph.com/clipart/cartoon-trash-can-gg58560651.html but instead of rubbish some keys, backup icon (https://www.kisspng.com/png-oracle-database-computer-icons-logo-encapsulated-p-852860/) etc. What do you think about it?

**Comment by noveoko** [comment]
Here's a new concept (sorry about the long delay between updates): https://imgur.com/a/tVo0I6h

**Comment by xep624** [comment]
Thanks @noveoko ! I try to get some feedback regarding it here: https://www.linkedin.com/feed/update/urn:li:activity:6511153240728432640 - let's see what community says.

**Comment by xep624** [comment]
Hi @noveoko ! I gathered some feedback and here are some suggestions:
- less details and more simpler (for example instead of those strings there could stand out from garbage a key and a yellow card with "myp@sswo4d"?)
- an alternative to the above can be that instead of strings there would be visible several 0s and 1s on the garbage like on this picture: https://www.123rf.com/photo_37467266_stock-vector-isolated-cartoon-of-binary-code-in-spilled-water.html
- can you also put some "evil face" to the dumpster? For example something similar to this: http://clipart-library.com/clipart/rinezj8iR.htm 

Would it be possible for you to apply such changes? Appreciate your help!

**Comment by securing** [comment]
The logo is already made and added, so I'm closing the issue.
